# Generated by Django 5.0 on 2026-04-23 18:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('stock', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('breed', models.CharField(max_length=100)),
                ('age_weeks', models.PositiveIntegerField(help_text='Age in weeks')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=2)),
                ('is_vaccinated', models.BooleanField(default=False)),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='PetFood',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('flavor', models.CharField(choices=[('CH', 'Chicken'), ('BF', 'Beef'), ('FG', 'Fish'), ('VG', 'Vegetarian')], max_length=2)),
                ('weight_kg', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('ingredients', models.TextField()),
                ('life_stage', models.CharField(choices=[('P', 'Puppy'), ('A', 'Adult'), ('S', 'Senior')], max_length=1)),
                ('flavour', models.CharField(blank=True, max_length=50, null=True)),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('material', models.CharField(choices=[('R', 'Rubber'), ('P', 'Plastic'), ('S', 'Soft'), ('W', 'Wood'), ('M', 'Metal')], max_length=1)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
                ('is_interactive', models.BooleanField(default=False)),
                ('durability_rating', models.IntegerField(default=3, help_text='Scale 1-5')),
                ('suitable_for', models.CharField(help_text='Suitable for which type of pets', max_length=100)),
            ],
            bases=('products.product',),
        ),
    ]
